# Generated by Django 4.2.11 on 2026-02-07 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('web', 'Веб-разработка'), ('mobile', 'Мобильная разработка'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('content', 'Контент'), ('other', 'Другое')], max_length=50, verbose_name='Категория')),
                ('experience', models.TextField(blank=True, verbose_name='Опыт работы')),
                ('availability', models.CharField(default='Готов к работе', max_length=100, verbose_name='Доступность')),
                ('price_per_project', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за проект')),
                ('currency', models.CharField(choices=[('RUB', 'Рубли'), ('USD', 'Доллары'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('skills', models.TextField(help_text='Перечислите через запятую', verbose_name='Навыки')),
                ('technologies', models.TextField(blank=True, verbose_name='Технологии')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для связи')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
