# Generated by Django 5.2.7 on 2025-12-11 14:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('category', models.CharField(choices=[('web', 'Веб-разработка'), ('mobile', 'Мобильная разработка'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('writing', 'Копирайтинг'), ('translation', 'Переводы'), ('other', 'Другое')], max_length=50, verbose_name='Категория')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бюджет')),
                ('currency', models.CharField(choices=[('RUB', '₽ Рубли'), ('USD', '$ Доллары'), ('EUR', '€ Евро')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('deadline', models.DateField(verbose_name='Срок выполнения')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='open', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tags', models.CharField(blank=True, help_text='Укажите через запятую', max_length=500, verbose_name='Теги')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_files/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Файл заказа',
                'verbose_name_plural': 'Файлы заказа',
            },
        ),
    ]
