# Generated by Django 4.2.11 on 2026-01-05 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_alter_orderfile_options_order_applications_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('canceled', 'Отменен'), ('closed', 'Закрыт'), ('cancelling', 'В процессе отмены')], default='open', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена'), ('revoked', 'Отозвана')], default='pending', max_length=20, verbose_name='Статус запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_cancellation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_cancellation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_request', to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Запрос на отмену',
                'verbose_name_plural': 'Запросы на отмену',
                'ordering': ['-created_at'],
            },
        ),
    ]
