# Generated by Django 4.2.11 on 2026-06-08 20:17

from django.db import migrations, models

def fill_categories(apps, schema_editor):
    Category = apps.get_model('order', 'Category')
    mapping = {
        'web': 'Веб-разработка',
        'mobile': 'Мобильная разработка',
        'design': 'Дизайн',
        'marketing': 'Маркетинг',
        'writing': 'Копирайтинг',
        'translation': 'Переводы',
        'other': 'Другое',
    }
    for slug, name in mapping.items():
        Category.objects.get_or_create(slug=slug, defaults={'name': name})

class Migration(migrations.Migration):
    dependencies = [('order', '0004_add_category_model')]
    operations = [
        migrations.RunPython(fill_categories, migrations.RunPython.noop),
    ]
    
class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status_cancellationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        
        
    ]
    
