# Generated by Django 4.2.11 on 2026-06-08 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_add_category_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.category', verbose_name='Категория FK'),
        ),
    ]
