# Generated by Django 4.2.11 on 2026-06-08 20:21

from django.db import migrations

def migrate_data(apps, schema_editor):
    Category = apps.get_model('order', 'Category')
    Order = apps.get_model('order', 'Order')
    
    # Сначала создаём категории если их нет
    mapping = {
        'web': 'Веб-разработка',
        'mobile': 'Мобильная разработка',
        'design': 'Дизайн',
        'marketing': 'Маркетинг',
        'writing': 'Копирайтинг',
        'translation': 'Переводы',
        'other': 'Другое',
    }
    for slug, name in mapping.items():
        Category.objects.get_or_create(slug=slug, defaults={'name': name})
    
    # Переносим данные
    for order in Order.objects.all():
        if order.category:
            order.category_new = Category.objects.get(slug=order.category)
            order.save()

class Migration(migrations.Migration):
    dependencies = [
    ('order', '0005_add_category_fk'),
]
    operations = [
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
    ]
