# Generated by Django 4.2.11 on 2026-06-08 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_migrate_category_data'),
    ]

    operations = [
    migrations.RemoveField(
        model_name='order',
        name='category',
    ),
    migrations.RenameField(
        model_name='order',
        old_name='category_new',
        new_name='category',
    ),
]
