# Generated by Django 4.2.11 on 2026-06-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_add_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='category',
        ),
        migrations.AddField(
            model_name='language',
            name='categories',
            field=models.ManyToManyField(blank=True, to='order.category', verbose_name='Категории'),
        ),
    ]
