# Generated by Django 4.2.11 on 2026-06-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_add_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='category',
        ),
    ]
