# Generated by Django 6.0.6 on 2026-07-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('canceled', 'Отменен'), ('pending_review', 'На проверке'), ('closed', 'Закрыт'), ('cancelling', 'В процессе отмены')], default='open', max_length=20, verbose_name='Статус'),
        ),
    ]
